title: "League of Legends Role Analysis"
email: "your-email@example.com"
description: "Analyzing the impact of roles in League of Legends esports matches."
baseurl: ""
url: "https://hassam303.github.io/League-of-Legends-Role-Analysis"

remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge
