title: "League of Legends Role Analysis"
email: "your-email@example.com"
description: "Analyzing the impact of roles in League of Legends esports matches."
baseurl: "" # Leave this empty unless your site is in a subdirectory
url: "https://hassam303.github.io/League-of-Legends-Role-Analysis"

# Use remote_theme for GitHub Pages
remote_theme: jekyll/minima

# Ensure necessary plugins are included
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge